<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_roles extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_roles_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'm_roles/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'm_roles/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'm_roles/index.html';
            $config['first_url'] = base_url() . 'm_roles/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->M_roles_model->total_rows($q);
        $m_roles = $this->M_roles_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'm_roles_data' => $m_roles,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('m_roles/m_roles_list', $data);
    }

    public function read($id) 
    {
        $row = $this->M_roles_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'kode' => $row->kode,
		'jenis' => $row->jenis,
	    );
            $this->load->view('m_roles/m_roles_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('m_roles'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('m_roles/create_action'),
	    'id' => set_value('id'),
	    'kode' => set_value('kode'),
	    'jenis' => set_value('jenis'),
	);
        $this->load->view('m_roles/m_roles_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'kode' => $this->input->post('kode',TRUE),
		'jenis' => $this->input->post('jenis',TRUE),
	    );

            $this->M_roles_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('m_roles'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->M_roles_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('m_roles/update_action'),
		'id' => set_value('id', $row->id),
		'kode' => set_value('kode', $row->kode),
		'jenis' => set_value('jenis', $row->jenis),
	    );
            $this->load->view('m_roles/m_roles_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('m_roles'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'kode' => $this->input->post('kode',TRUE),
		'jenis' => $this->input->post('jenis',TRUE),
	    );

            $this->M_roles_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('m_roles'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->M_roles_model->get_by_id($id);

        if ($row) {
            $this->M_roles_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('m_roles'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('m_roles'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('kode', 'kode', 'trim|required');
	$this->form_validation->set_rules('jenis', 'jenis', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file M_roles.php */
/* Location: ./application/controllers/M_roles.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-10-23 08:17:17 */
/* http://harviacode.com */